# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plerpingapp',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
