# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeroplayergame',
            name='extraIncludes',
            field=models.ManyToManyField(blank=True, null=True, to='game.JSLibrary'),
        ),
    ]
