# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20160220_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeroplayergame',
            name='mainImage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
