# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 07:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_thumbs.db.models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_auto_20160126_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('seed', jsonfield.fields.JSONField()),
                ('source', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='GameInstanceSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_thumbs.db.models.ImageWithThumbsField(upload_to=b'')),
                ('time', models.FloatField(default=0)),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='game.GameInstance')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.GameInstance')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=django_thumbs.db.models.ImageWithThumbsField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='zeroplayergame',
            name='image',
            field=django_thumbs.db.models.ImageWithThumbsField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='zeroplayergame',
            name='scriptName',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='zeroplayergame',
            name='scriptType',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gameinstance',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.ZeroPlayerGame'),
        ),
        migrations.AddField(
            model_name='gameinstance',
            name='instantiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
