# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20160427_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seedvectorparam',
            name='app',
        ),
    ]
