# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 00:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20160127_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zeroplayergame',
            name='defaultSeed',
        ),
        migrations.AddField(
            model_name='gameinstance',
            name='pagecache',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='gameinstancesnapshot',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 28, 0, 29, 1, 712735, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameinstance',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
