# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_savedfunction_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedfunction',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
