# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 02:56
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20160128_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='zeroplayergame',
            name='seedStruct',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
