# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20160323_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(choices=[('javascript', 'text/javascript'), ('coffeescript', 'text/coffeescript'), ('paperscript', 'text/paperscript')], default='javascript', max_length=20)),
                ('source', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='savedfunction',
            name='language',
            field=models.CharField(choices=[('javascript', 'text/javascript'), ('coffeescript', 'text/coffeescript'), ('paperscript', 'text/paperscript')], default='javascript', max_length=20),
        ),
    ]
