# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_zeroplayergame_seedstruct'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='game.ZeroPlayerGame')),
            ],
        ),
    ]
