# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20160323_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='zeroplayergame',
            name='required_modules',
            field=models.ManyToManyField(null=True, to='game.CodeModule'),
        ),
    ]
