# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 04:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20160129_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zeroplayergame',
            name='seedStruct',
        ),
    ]
