# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_zeroplayergame_required_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeroplayergame',
            name='required_modules',
            field=models.ManyToManyField(blank=True, null=True, to='game.CodeModule'),
        ),
    ]
