# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20160325_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeroplayergame',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='game.Category'),
        ),
    ]
