# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20160401_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='popularity',
            field=models.IntegerField(default=1),
        ),
    ]
