# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20160129_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinstance',
            name='pagecache',
            field=models.TextField(blank=True, null=True),
        ),
    ]
