# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_category_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinstance',
            name='popularity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='zeroplayergame',
            name='popularity',
            field=models.IntegerField(default=1),
        ),
    ]
