# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20160129_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinstance',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='game.ZeroPlayerGame'),
        ),
    ]
