# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20160129_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinstance',
            name='source',
        ),
    ]
