# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20160410_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedkeyval',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
