# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_auto_20160410_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinstance',
            name='vector',
            field=models.CharField(max_length=5000, null=True, unique=True),
        ),
    ]
