# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_gameinstance_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedKeyValRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='gameinstance',
            name='seedParams',
        ),
        migrations.AddField(
            model_name='seedkeyvalrelationship',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.GameInstance'),
        ),
        migrations.AddField(
            model_name='seedkeyvalrelationship',
            name='keyval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.SeedKeyVal'),
        ),
        migrations.AddField(
            model_name='gameinstance',
            name='sprams',
            field=models.ManyToManyField(blank=True, null=True, through='game.SeedKeyValRelationship', to='game.SeedKeyVal'),
        ),
    ]
