# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_remove_zeroplayergame_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scriptPath', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='zeroplayergame',
            name='extraIncludes',
            field=models.ManyToManyField(to='game.JSLibrary'),
        ),
    ]
