# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_auto_20160411_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedkeyval',
            name='valtype',
            field=models.CharField(default='string', max_length=25),
        ),
    ]
