# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_seedkeyval_valtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinstance',
            name='sprams',
        ),
        migrations.AddField(
            model_name='gameinstance',
            name='seedParams',
            field=models.ManyToManyField(blank=True, null=True, to='game.SeedKeyVal'),
        ),
    ]
