# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_auto_20160411_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinstance',
            name='seedParams',
            field=models.ManyToManyField(blank=True, null=True, related_name='params', to='game.SeedKeyVal'),
        ),
    ]
