# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_auto_20160411_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
