# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0004_auto_20160206_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='extraIncludes',
            field=models.ManyToManyField(blank=True, null=True, related_name='included_in', to='exhibitions.JSLibrary'),
        ),
    ]
