# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0007_auto_20160206_0356'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('followers', models.ManyToManyField(related_name='followees', to='exhibitions.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='app',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='exhibitions.User'),
        ),
        migrations.AlterField(
            model_name='appinstance',
            name='instantiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibitions.User'),
        ),
    ]
