# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20160126_1004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlerpingApp',
            new_name='App',
        ),
    ]
