# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20160127_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='App',
            name='image',
        ),
        migrations.AddField(
            model_name='App',
            name='defaultSeed',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='App',
            name='source',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gameinstance',
            name='source',
            field=models.TextField(),
        ),
    ]
