# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_gameparam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameparam',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='params', to='game.App'),
        ),
    ]
