# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_remove_zeroplayergame_seedstruct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameparam',
            name='game',
        ),
        migrations.AddField(
            model_name='zeroplayergame',
            name='seedStructure',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gameinstance',
            name='seed',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='GameParam',
        ),
    ]
