# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django_thumbs.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_remove_gameinstance_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_thumbs.db.models.ImageWithThumbsField(upload_to=b'')),
            ],
        ),
    ]
