# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 14:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django_thumbs.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_auto_20160204_0727'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageTest',
        ),
        migrations.AlterModelOptions(
            name='jslibrary',
            options={'verbose_name_plural': 'JS libraries'},
        ),
        migrations.RenameField(
            model_name='gameinstance',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='gameinstancesnapshot',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='gameinstance',
            name='pagecache',
        ),
        migrations.RemoveField(
            model_name='zeroplayergame',
            name='scriptName',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='game.Category'),
        ),
        migrations.AddField(
            model_name='gameinstance',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 18, 14, 34, 17, 339458, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameinstancesnapshot',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 18, 14, 34, 28, 447981, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zeroplayergame',
            name='mainImage',
            field=django_thumbs.db.models.ImageWithThumbsField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='zeroplayergame',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='game.App'),
        ),
        migrations.AddField(
            model_name='zeroplayergame',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 18, 14, 34, 38, 941079, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zeroplayergame',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
