# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='Poofaloofist', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
