# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_thumbs.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_thumbs.db.models.ImageWithThumbsField(upload_to=b'')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.ImageGallery')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('image', django_thumbs.db.models.ImageWithThumbsField(null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField()),
                ('sourcecode', models.CharField(max_length=200, null=True)),
                ('image', django_thumbs.db.models.ImageWithThumbsField(null=True, upload_to=b'')),
                ('creationdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProprietaryPortfolioItem',
            fields=[
                ('portfolioitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio.PortfolioItem')),
                ('company', models.CharField(max_length=100)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.ImageGallery')),
            ],
            bases=('portfolio.portfolioitem',),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.PortfolioCategory'),
        ),
    ]
