# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='url',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
