# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolioitem_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='sourcecode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
