# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appinstance',
            old_name='game',
            new_name='app',
        ),
        migrations.RemoveField(
            model_name='app',
            name='created',
        ),
        migrations.RemoveField(
            model_name='app',
            name='scriptName',
        ),
        migrations.RemoveField(
            model_name='appinstance',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='snapshot',
            name='timestamp',
        ),
    ]
