# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0002_auto_20160206_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='parent',
            field=models.ManyToManyField(related_name='children', to='exhibitions.App'),
        ),
    ]
