# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0003_app_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='exhibitions.Category'),
        ),
        migrations.RemoveField(
            model_name='app',
            name='parent',
        ),
        migrations.AddField(
            model_name='app',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='exhibitions.App'),
        ),
    ]
